#!/usr/bin/env bash
# One build cache per worktree, forked from the main checkout's.
#
#     bash scripts/build-cache.sh setup    in the main checkout, and again after `rustup update`
#     bash scripts/build-cache.sh prime    in the main checkout, after a merge into develop
#     bash scripts/build-cache.sh gc       drop the caches of worktrees that are gone
#
# The main checkout builds into <main>/target/base. `setup` in a worktree copies that cache to
# <main>/target/wt-<name> and points the worktree at the copy, so a new worktree starts with all
# 339 dependencies built and compiles only the workspace's own crates: 1 min on a fork instead of
# 3.5 min from nothing, and every edit after that 6-11 s. When the worktree is gone, `gc` drops
# its cache. In a new worktree both happen by themselves: scripts/hooks/post-checkout runs them
# when `git worktree add` creates it, once `git config core.hooksPath scripts/hooks` is set.
#
# Why not one cache for everyone: rustc keeps one incremental session per crate, and two
# worktrees building into the same target/ overwrite each other's session. Every switch between
# them was a full recompile of app and server -- 200 s instead of 14 s.
#
# Why the workspace crates always compile once on a fork: the incremental session records
# absolute paths and is worthless anywhere else, so it is left out of the copy, together with
# the executables. What the copy carries are the dependencies, which do not care where they
# are used from.
#
# It also writes the flags: --cfg erase_components, which spares rustc the types of the Leptos
# components (folia-app 96 s -> 35 s, folia-server 61 s -> 13 s; the bundle that ships is built
# without it), and rust-lld instead of mingw's ld, which the toolchain ships but gcc only finds
# when pointed at the toolchain's gcc-ld shims (24 s -> 19 s per rebuild). The linker is a path
# on this machine, so .cargo/config.toml is generated and not in git -- and base and forks must
# be built with identical flags for the copy to be of any use, which is why one script writes
# both.
set -euo pipefail
cd "$(dirname "$0")/.."

gitdir=$(git rev-parse --path-format=absolute --git-dir)
common=$(git rev-parse --path-format=absolute --git-common-dir)
main=$(dirname "$common")
root="$main/target"
base="$root/base"
here=$(git rev-parse --show-toplevel)

if [ "$gitdir" = "$common" ]; then
  cache="$base"
else
  cache="$root/wt-$(basename "$here")"
fi

write_config() {
  local host sysroot shims
  host=$(rustc -vV | sed -n 's/^host: //p')
  sysroot=$(rustc --print sysroot | tr -s '\134' '/')
  shims="$sysroot/lib/rustlib/$host/bin/gcc-ld"
  mkdir -p .cargo
  {
    echo "# Generated by scripts/build-cache.sh -- machine-local, not in git."
    echo
    echo "[build]"
    echo "target-dir = \"$cache\""
    # Cargo reads the .cargo/config.toml of every directory above the one it runs in and joins
    # their lists. A worktree inside the main checkout (.claude/worktrees/<name>) therefore has
    # the main checkout's flags already; written here too, they would stand there twice, and
    # since the flags are part of every unit's fingerprint, none of the fork's 415 units would
    # count as built (5 min 20 s instead of 3 min). Such a worktree takes the flags from above,
    # which are the ones base is built with.
    case "$here/" in
      "$main"/?*/)
        echo
        echo "# The flags: $main/.cargo/config.toml"
        ;;
      *) flags "$host" "$shims" ;;
    esac
  } > .cargo/config.toml
}

# The flags every build is made with, base and forks alike.
flags() {
  local host=$1 shims=$2
  echo
  echo "[target.$host]"
  echo "rustflags = ["
  echo "    # Leptos without the types of the components (docs/frontend.md §3)."
  echo "    \"--cfg=erase_components\","
  case "$host" in
    *-pc-windows-gnu)
      if [ -d "$shims" ]; then
        echo "    # rust-lld instead of mingw's ld."
        echo "    \"-Clink-arg=-fuse-ld=lld\","
        echo "    \"-Clink-arg=-B$shims\","
      else
        echo "no lld shims at $shims: linking with the default linker" >&2
      fi
      ;;
  esac
  echo "]"
  echo
  echo "# The browser app as build-client.sh --dev builds it. The bundle that ships is built"
  echo "# without the flags of this file, as Nix builds it."
  echo "[target.wasm32-unknown-unknown]"
  echo "rustflags = [\"--cfg=erase_components\"]"
}

fork() {
  echo "forking $base"
  echo "     to $cache"
  mkdir -p "$cache"
  # The owner first: a gc started by another new worktree (the hook runs it in the background)
  # drops every cache without one, and would take this one while it is still being copied.
  printf '%s\n' "$here" > "$cache/.worktree"
  # Not the incremental sessions (bound to base's paths) and not the executables (the
  # workspace's own, 1.2 GB for the server alone): both are rebuilt here anyway. Build scripts'
  # executables sit deeper and are kept -- without them every build script would run again.
  tar -C "$base" --no-wildcards-match-slash \
      --exclude=incremental --exclude='debug/*.exe' --exclude='deps/*.exe' \
      -cf - . | tar -C "$cache" -xf -
  # cargo decides what is stale by modification time. A file here that differs from base but
  # is older than base's artefacts -- edited before base was last built -- would count as
  # built, and the worktree would run the main checkout's code. Newer than anything in the
  # copy, every workspace source is compiled again, as it would be on a fresh worktree anyway.
  git ls-files -z -- app catalog client pack server | xargs -0 touch
}

case "${1:-}" in
  setup)
    if [ "$cache" = "$base" ]; then
      echo "main checkout: builds into $base, the cache every worktree forks from"
    elif [ -d "$cache" ]; then
      echo "keeps its cache $cache"
    elif [ -d "$base/debug" ]; then
      fork
    else
      echo "no base yet ($base): this worktree starts from nothing." >&2
      echo "run 'bash scripts/build-cache.sh prime' in $main to spare the next one." >&2
    fi
    if [ "$cache" != "$base" ]; then
      # Whose cache this is, for gc. Not taken from `git worktree list`: a worktree moved along
      # with its repository stays registered under the old path until `git worktree repair`.
      mkdir -p "$cache"
      printf '%s\n' "$here" > "$cache/.worktree"
    fi
    write_config
    echo "wrote .cargo/config.toml"
    ;;

  prime)
    [ "$cache" = "$base" ] || { echo "prime builds the base: run it in the main checkout, $main" >&2; exit 1; }
    write_config
    cargo build
    cargo test --no-run
    # The browser app's dependencies too, or every worktree's first `build-client.sh --dev`
    # starts from nothing (3.5 min).
    if rustup target list --installed 2>/dev/null | grep -q '^wasm32-unknown-unknown$'; then
      cargo build -p folia-client --target wasm32-unknown-unknown --profile wasm-dev
    else
      echo "no wasm32-unknown-unknown target: the browser app is not in the base" >&2
    fi
    echo "base is built: $base"
    ;;

  gc)
    freed=0
    for dir in "$root"/wt-*/; do
      [ -d "$dir" ] || continue
      dir=${dir%/}
      owner=$(cat "$dir/.worktree" 2>/dev/null || true)
      # A worktree has a .git file at its top; a directory that merely still exists does not
      # count, nor does a cache that never recorded its owner.
      if [ -n "$owner" ] && [ -e "$owner/.git" ]; then continue; fi
      echo "dropping $dir ($(du -sh "$dir" | cut -f1)): ${owner:-owner unknown} is gone"
      rm -rf "$dir"
      freed=1
    done
    [ "$freed" = 1 ] || echo "every cache belongs to a worktree that still exists"
    ;;

  *)
    echo "usage: $0 setup|prime|gc" >&2
    exit 2
    ;;
esac
